[features]
seeds = false

[programs.devnet]
funding_block = "Gfaf2UDB7aYzbBcZGHtAzyR3BtMubkm5EBhxGdzgwcs"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/macintosh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
